### ISSUE TITLE
[DrawActivity][Really later]Android 6.0 request permission needs user prompt

### ISSUE THREAD

**Issue by masteret** [killVung/banana-scaler#1]
Ka
We can do this on the side, because the standard is 5.0

Oh shit! Why am I talking to myself
Hi! How am I?
I am fine thank you

**Comment by masteret** [comment]
http://developer.android.com/training/permissions/requesting.html

**Comment by killvung** [comment]
Why is Ka talking to himself

That's because Ka is a Psychopath
